# Generated by Django 5.2.8 on 2025-12-02 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scribble', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='scribblepointinfo',
            name='image_name',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
